
version: 2

models:
    - name: consultas-ventas-clientes
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: consulta-producto-proveedores
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      
    - name: consulta-producto-proveedores
      description: "A starter dbt model"
      columns:
          - name: nombre_region
            description: "The name of region"
            tests:
                - not_null
